name: 'build-test'
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
      - name: test
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          masterBranchName: main
          value: v1.0.1
          branch: deployment/v1.0.1
          targetBranch: main
          createPR: 'false'
          message: 'Update Image Version to v1.0.1'
          token: ${{ steps.app-token.outputs.token }}
      - name: test-no-changes-did-not-fail
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          masterBranchName: main
          value: v1.2.0
          branch: deployment/v1.2.0
          targetBranch: main
          createPR: 'false'
          message: 'Update Image Version to v1.2.0'
          token: ${{ steps.app-token.outputs.token }}
      - name: test-target-repository
        uses: ./infrastructure
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          value: v1.2.1
          masterBranchName: main
          branch: deployment/v1.2.1
          targetBranch: main
          createPR: 'false'
          message: 'Update Image Version to v1.2.1' 
          workDir: infrastructure
          token: ${{ steps.app-token.outputs.token }}
      - name: test-update-file
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          value: v1.0.1
          masterBranchName: main
          commitChange: 'false'
          updateFile: 'true'
      - name:  test-multiple-file-changes
        uses: ./
        with:
          branch: deployment/test-multi-file-update
          masterBranchName: main
          createPR: 'false'
          targetBranch: main
          description: Test GitHub Action
          message: 'Update All Images' 
          title: 'Version Updates on all Environments'
          changes: |
            {
              "__tests__/fixtures/values.json": {
                "backend.version": "v1.0.1",
                "frontend": true
              },
              "__tests__/fixtures/values.dev.yaml": {
                "backend.version": "v1.0.1",
                "frontend": true
              },
              "__tests__/fixtures/values.stage.yaml": {
                "backend.version": "v1.0.1",
                "frontend": true
              },
              "__tests__/fixtures/values.prod.yaml": {
                "backend.version": "v1.0.1",
                "frontend": true
              }
            }
      - name: test-value-types
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'config.prod'
          value: "!!bool 'true'"
          branch: deployment/test-bool-value
          masterBranchName: main
          targetBranch: main
          description: Test GitHub Action
          message: 'Update Config' 
          title: 'Bool Update on all Environments'
          token: ${{ steps.app-token.outputs.token }}
      - name: test-value-types-2
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'config.version'
          value: "!!int '1234'"
          branch: deployment/test-int-value
          masterBranchName: main
          targetBranch: main
          description: Test GitHub Action
          message: 'Update Config' 
          title: 'Int Update on all Environments'
          token: ${{ steps.app-token.outputs.token }}

  cleanup:
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v3
      - name: Delete test branches
        uses: dawidd6/action-delete-branch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          branches: deployment/v1.2.1,deployment/v1.0.1,deployment/test-bool-value,deployment/test-int-value,deployment/test-multi-file-update
